name: YZVF
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py38hecd8cb5_1001
  - argon2-cffi=20.1.0=py38h9ed2024_1
  - astroid=2.4.1=py38_0
  - astropy=4.0.1.post1=py38h01d97ff_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - blosc=1.21.0=h2842e9f_0
  - bokeh=2.3.3=py38hecd8cb5_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2021.10.26=hecd8cb5_2
  - certifi=2021.10.8=py38hecd8cb5_2
  - cffi=1.15.0=py38hca72f7f_0
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=h18a8e69_0
  - debugpy=1.5.1=py38he9d5cce_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.4.1=h23ab428_2
  - freetype=2.11.0=hd8bbffd_0
  - gettext=0.21.0=h7535e17_0
  - giflib=5.2.1=haf1e3a3_0
  - glib=2.63.1=hd977a24_0
  - hdf5=1.10.4=hfa1e0ec_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=4.8.1=py38hecd8cb5_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - ipykernel=6.4.1=py38hecd8cb5_1
  - ipython=7.29.0=py38h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=4.3.21=py38_0
  - jedi=0.18.0=py38hecd8cb5_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h9ed2024_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.0.6=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py38h23ab428_0
  - lazy-object-proxy=1.4.3=py38h1de35cc_0
  - lcms2=2.12=hf1fd2bf_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.2.1=1
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libtiff=4.2.0=h87d7836_0
  - libwebp=1.2.0=hacca55c_0
  - libwebp-base=1.2.0=h9ed2024_0
  - libxml2=2.9.12=hcdb78fc_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - lz4-c=1.9.3=h23ab428_1
  - lzo=2.10=haf1e3a3_2
  - markupsafe=2.0.1=py38h9ed2024_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h9aa3819_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h1de35cc_1001
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38h9ed2024_0
  - mkl_fft=1.3.0=py38ha059aab_0
  - mkl_random=1.1.1=py38h959d312_0
  - mock=4.0.3=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=hca72f7f_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.6=py38hecd8cb5_0
  - numexpr=2.7.3=py38h16bde0e_0
  - numpy=1.18.1=py38h7241aed_0
  - numpy-base=1.18.1=py38h3304bdc_1
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1m=hca72f7f_0
  - opentsne=0.6.0=py38he35c9cc_1
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.2.4=py38hb2f4e1b_0
  - pandocfilters=1.4.3=py38hecd8cb5_1
  - parso=0.8.2=pyhd3eb1b0_0
  - patsy=0.5.2=py38hecd8cb5_0
  - pcre=8.45=h23ab428_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py38h98e4679_0
  - pip=20.1.1=py38_1
  - plotly=4.14.3=pyhd3eb1b0_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pylint=2.5.0=py38_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.18.0=py38hca72f7f_0
  - pytables=3.6.1=py38h4727e94_0
  - python=3.8.2=hc70fcce_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py38hca72f7f_1
  - pyzmq=22.2.1=py38h23ab428_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1=h9ed2024_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - scikit-learn=1.0.1=py38hae1ba45_0
  - scipy=1.6.2=py38h2515648_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38hecd8cb5_0
  - sip=4.19.8=py38h0a44026_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hce871da_0
  - statsmodels=0.11.1=py38haf1e3a3_0
  - terminado=0.9.4=py38hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h7bc2e8c_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.1=py38h9ed2024_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.11.2=py38h1de35cc_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.9=h322a384_0
  - pip:
    - adjusttext==0.7.3
    - bioinfokit==2.0.4
    - data==0.4
    - funcsigs==1.0.2
    - future==0.18.2
    - latex==0.7.0
    - matplotlib-venn==0.11.6
    - shutilwhich==1.1.0
    - tabulate==0.8.9
    - tempdir==0.7.1
    - textwrap3==0.9.2
    - traitlets==4.3.3
prefix: /Users/yunluzhu/opt/miniconda3/envs/YZVF

